#############################################################################
# Makefile for building: OCR
# Generated by qmake (3.0) (Qt 5.6.0)
# Project:  OCR.pro
# Template: app
# Command: /home/erfan/Qt5.6.0/5.6/gcc_64/bin/qmake -spec linux-g++ -o Makefile OCR.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/include/opencv -I/usr/local/include -I../../Qt5.6.0/5.6/gcc_64/include -I../../Qt5.6.0/5.6/gcc_64/include/QtCore -I. -I../../Qt5.6.0/5.6/gcc_64/mkspecs/linux-g++
QMAKE         = /home/erfan/Qt5.6.0/5.6/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = OCR1.0.0
DISTDIR = /home/erfan/OCR/LetterRecognizer/.tmp/OCR1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-z,origin -Wl,-rpath,\$$ORIGIN -Wl,-rpath,/home/erfan/Qt5.6.0/5.6/gcc_64/lib
LIBS          = $(SUBLIBS) -L/usr/local/lib/ -L/usr/local/lib -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_cvv -lopencv_dnn -lopencv_dpm -lopencv_fuzzy -lopencv_line_descriptor -lopencv_plot -lopencv_reg -lopencv_saliency -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_rgbd -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_text -lopencv_face -lopencv_xfeatures2d -lopencv_calib3d -lopencv_features2d -lopencv_shape -lopencv_video -lopencv_flann -lopencv_xobjdetect -lopencv_objdetect -lopencv_ml -lopencv_xphoto -lippicv -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_photo -lopencv_imgproc -lopencv_core -L/home/erfan/Qt5.6.0/5.6/gcc_64/lib -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		farsi_ocr/cvBlobsLib/blob.cpp \
		farsi_ocr/cvBlobsLib/BlobContour.cpp \
		farsi_ocr/cvBlobsLib/BlobOperators.cpp \
		farsi_ocr/cvBlobsLib/BlobResult.cpp \
		farsi_ocr/cvBlobsLib/ComponentLabeling.cpp \
		farsi_ocr/Character.cpp \
		farsi_ocr/DistanceProfile.cpp \
		farsi_ocr/functions.cpp \
		farsi_ocr/lettetRecognizer.cpp 
OBJECTS       = main.o \
		blob.o \
		BlobContour.o \
		BlobOperators.o \
		BlobResult.o \
		ComponentLabeling.o \
		Character.o \
		DistanceProfile.o \
		functions.o \
		lettetRecognizer.o
DIST          = ../../Qt5.6.0/5.6/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/common/unix.conf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/common/linux.conf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/qconfig.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/spec_post.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/default_post.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/link_pkgconfig.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/qt.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/resources.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/moc.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/yacc.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/lex.prf \
		OCR.pro farsi_ocr/cvBlobsLib/blob.h \
		farsi_ocr/cvBlobsLib/BlobContour.h \
		farsi_ocr/cvBlobsLib/BlobLibraryConfiguration.h \
		farsi_ocr/cvBlobsLib/BlobOperators.h \
		farsi_ocr/cvBlobsLib/BlobResult.h \
		farsi_ocr/cvBlobsLib/ComponentLabeling.h \
		farsi_ocr/Character.h \
		farsi_ocr/DistanceProfile.h \
		farsi_ocr/functions.h \
		tiny-cnn/activation_function.h \
		tiny-cnn/average_pooling_layer.h \
		tiny-cnn/cifar10_parser.h \
		tiny-cnn/config.h \
		tiny-cnn/convolutional_layer.h \
		tiny-cnn/deform.h \
		tiny-cnn/display.h \
		tiny-cnn/dropout.h \
		tiny-cnn/fully_connected_dropout_layer.h \
		tiny-cnn/fully_connected_layer.h \
		tiny-cnn/image.h \
		tiny-cnn/input_layer.h \
		tiny-cnn/layer.h \
		tiny-cnn/layers.h \
		tiny-cnn/loss_function.h \
		tiny-cnn/max_pooling_layer.h \
		tiny-cnn/mnist_parser.h \
		tiny-cnn/network.h \
		tiny-cnn/optimizer.h \
		tiny-cnn/partial_connected_layer.h \
		tiny-cnn/product.h \
		tiny-cnn/tiny_cnn.h \
		tiny-cnn/util.h \
		tiny-cnn/weight_init.h \
		farsi_ocr/letterRecognizer.h main.cpp \
		farsi_ocr/cvBlobsLib/blob.cpp \
		farsi_ocr/cvBlobsLib/BlobContour.cpp \
		farsi_ocr/cvBlobsLib/BlobOperators.cpp \
		farsi_ocr/cvBlobsLib/BlobResult.cpp \
		farsi_ocr/cvBlobsLib/ComponentLabeling.cpp \
		farsi_ocr/Character.cpp \
		farsi_ocr/DistanceProfile.cpp \
		farsi_ocr/functions.cpp \
		farsi_ocr/lettetRecognizer.cpp
QMAKE_TARGET  = OCR
DESTDIR       = 
TARGET        = OCR


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: OCR.pro ../../Qt5.6.0/5.6/gcc_64/mkspecs/linux-g++/qmake.conf ../../Qt5.6.0/5.6/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/common/unix.conf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/common/linux.conf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/qconfig.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/spec_post.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/default_post.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/link_pkgconfig.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/qt.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/resources.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/moc.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/yacc.prf \
		../../Qt5.6.0/5.6/gcc_64/mkspecs/features/lex.prf \
		OCR.pro \
		../../Qt5.6.0/5.6/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ -o Makefile OCR.pro
../../Qt5.6.0/5.6/gcc_64/mkspecs/features/spec_pre.prf:
../../Qt5.6.0/5.6/gcc_64/mkspecs/common/unix.conf:
../../Qt5.6.0/5.6/gcc_64/mkspecs/common/linux.conf:
../../Qt5.6.0/5.6/gcc_64/mkspecs/common/sanitize.conf:
../../Qt5.6.0/5.6/gcc_64/mkspecs/common/gcc-base.conf:
../../Qt5.6.0/5.6/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Qt5.6.0/5.6/gcc_64/mkspecs/common/g++-base.conf:
../../Qt5.6.0/5.6/gcc_64/mkspecs/common/g++-unix.conf:
../../Qt5.6.0/5.6/gcc_64/mkspecs/qconfig.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.6.0/5.6/gcc_64/mkspecs/features/qt_functions.prf:
../../Qt5.6.0/5.6/gcc_64/mkspecs/features/qt_config.prf:
../../Qt5.6.0/5.6/gcc_64/mkspecs/linux-g++/qmake.conf:
../../Qt5.6.0/5.6/gcc_64/mkspecs/features/spec_post.prf:
../../Qt5.6.0/5.6/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Qt5.6.0/5.6/gcc_64/mkspecs/features/default_pre.prf:
../../Qt5.6.0/5.6/gcc_64/mkspecs/features/resolve_config.prf:
../../Qt5.6.0/5.6/gcc_64/mkspecs/features/default_post.prf:
../../Qt5.6.0/5.6/gcc_64/mkspecs/features/link_pkgconfig.prf:
../../Qt5.6.0/5.6/gcc_64/mkspecs/features/warn_on.prf:
../../Qt5.6.0/5.6/gcc_64/mkspecs/features/qt.prf:
../../Qt5.6.0/5.6/gcc_64/mkspecs/features/resources.prf:
../../Qt5.6.0/5.6/gcc_64/mkspecs/features/moc.prf:
../../Qt5.6.0/5.6/gcc_64/mkspecs/features/unix/thread.prf:
../../Qt5.6.0/5.6/gcc_64/mkspecs/features/testcase_targets.prf:
../../Qt5.6.0/5.6/gcc_64/mkspecs/features/exceptions.prf:
../../Qt5.6.0/5.6/gcc_64/mkspecs/features/yacc.prf:
../../Qt5.6.0/5.6/gcc_64/mkspecs/features/lex.prf:
OCR.pro:
../../Qt5.6.0/5.6/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ -o Makefile OCR.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents farsi_ocr/cvBlobsLib/blob.h farsi_ocr/cvBlobsLib/BlobContour.h farsi_ocr/cvBlobsLib/BlobLibraryConfiguration.h farsi_ocr/cvBlobsLib/BlobOperators.h farsi_ocr/cvBlobsLib/BlobResult.h farsi_ocr/cvBlobsLib/ComponentLabeling.h farsi_ocr/Character.h farsi_ocr/DistanceProfile.h farsi_ocr/functions.h tiny-cnn/activation_function.h tiny-cnn/average_pooling_layer.h tiny-cnn/cifar10_parser.h tiny-cnn/config.h tiny-cnn/convolutional_layer.h tiny-cnn/deform.h tiny-cnn/display.h tiny-cnn/dropout.h tiny-cnn/fully_connected_dropout_layer.h tiny-cnn/fully_connected_layer.h tiny-cnn/image.h tiny-cnn/input_layer.h tiny-cnn/layer.h tiny-cnn/layers.h tiny-cnn/loss_function.h tiny-cnn/max_pooling_layer.h tiny-cnn/mnist_parser.h tiny-cnn/network.h tiny-cnn/optimizer.h tiny-cnn/partial_connected_layer.h tiny-cnn/product.h tiny-cnn/tiny_cnn.h tiny-cnn/util.h tiny-cnn/weight_init.h farsi_ocr/letterRecognizer.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp farsi_ocr/cvBlobsLib/blob.cpp farsi_ocr/cvBlobsLib/BlobContour.cpp farsi_ocr/cvBlobsLib/BlobOperators.cpp farsi_ocr/cvBlobsLib/BlobResult.cpp farsi_ocr/cvBlobsLib/ComponentLabeling.cpp farsi_ocr/Character.cpp farsi_ocr/DistanceProfile.cpp farsi_ocr/functions.cpp farsi_ocr/lettetRecognizer.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp ../../Qt5.6.0/5.6/gcc_64/include/QtCore/QCoreApplication \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qcoreapplication.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qglobal.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qconfig.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qfeatures.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qisenum.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qlogging.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qflags.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_x86.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_unix.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qmutex.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qnumeric.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qversiontagging.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qstring.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qchar.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qbytearray.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qrefcount.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qnamespace.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qarraydata.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qobject.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qlist.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qiterator.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qhashfunctions.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qpair.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qstringlist.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qregexp.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qmetatype.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qeventloop.h \
		farsi_ocr/letterRecognizer.h \
		/usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/photo.hpp \
		/usr/local/include/opencv2/photo/photo_c.h \
		/usr/local/include/opencv2/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/video/tracking_c.h \
		/usr/local/include/opencv2/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/objdetect.hpp \
		/usr/local/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/include/opencv2/objdetect/objdetect_c.h \
		/usr/local/include/opencv2/calib3d.hpp \
		/usr/local/include/opencv2/core/affine.hpp \
		/usr/local/include/opencv2/calib3d/calib3d_c.h \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/ml.hpp \
		/usr/local/include/opencv2/ml/ml.hpp \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/QDir \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qdir.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qfileinfo.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qfile.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qfiledevice.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qiodevice.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qshareddata.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qhash.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/QStringList \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/QDebug \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qdebug.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qmap.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qtextstream.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qlocale.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qvariant.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qvector.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qpoint.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qset.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qcontiguouscache.h \
		tiny-cnn/tiny_cnn.h \
		tiny-cnn/network.h \
		tiny-cnn/util.h \
		tiny-cnn/activation_function.h \
		tiny-cnn/loss_function.h \
		tiny-cnn/optimizer.h \
		tiny-cnn/layer.h \
		tiny-cnn/product.h \
		tiny-cnn/image.h \
		tiny-cnn/weight_init.h \
		tiny-cnn/layers.h \
		tiny-cnn/input_layer.h \
		tiny-cnn/fully_connected_layer.h \
		tiny-cnn/dropout.h \
		tiny-cnn/average_pooling_layer.h \
		tiny-cnn/partial_connected_layer.h \
		tiny-cnn/convolutional_layer.h \
		tiny-cnn/fully_connected_dropout_layer.h \
		tiny-cnn/max_pooling_layer.h \
		tiny-cnn/mnist_parser.h \
		tiny-cnn/cifar10_parser.h \
		tiny-cnn/deform.h \
		tiny-cnn/display.h \
		/usr/local/include/opencv2/xfeatures2d.hpp \
		/usr/local/include/opencv2/xfeatures2d/nonfree.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

blob.o: farsi_ocr/cvBlobsLib/blob.cpp farsi_ocr/cvBlobsLib/blob.h \
		/usr/local/include/opencv/cxcore.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/photo.hpp \
		/usr/local/include/opencv2/photo/photo_c.h \
		/usr/local/include/opencv2/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/video/tracking_c.h \
		/usr/local/include/opencv2/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/objdetect.hpp \
		/usr/local/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/include/opencv2/objdetect/objdetect_c.h \
		/usr/local/include/opencv2/calib3d.hpp \
		/usr/local/include/opencv2/core/affine.hpp \
		/usr/local/include/opencv2/calib3d/calib3d_c.h \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/ml.hpp \
		farsi_ocr/cvBlobsLib/BlobLibraryConfiguration.h \
		farsi_ocr/cvBlobsLib/BlobContour.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o blob.o farsi_ocr/cvBlobsLib/blob.cpp

BlobContour.o: farsi_ocr/cvBlobsLib/BlobContour.cpp farsi_ocr/cvBlobsLib/BlobContour.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/photo/photo_c.h \
		/usr/local/include/opencv2/video/tracking_c.h \
		/usr/local/include/opencv2/objdetect/objdetect_c.h \
		/usr/local/include/opencv/cxcore.h \
		/usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/photo.hpp \
		/usr/local/include/opencv2/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/objdetect.hpp \
		/usr/local/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/include/opencv2/calib3d.hpp \
		/usr/local/include/opencv2/core/affine.hpp \
		/usr/local/include/opencv2/calib3d/calib3d_c.h \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/ml.hpp \
		/usr/local/include/opencv2/core/core.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BlobContour.o farsi_ocr/cvBlobsLib/BlobContour.cpp

BlobOperators.o: farsi_ocr/cvBlobsLib/BlobOperators.cpp farsi_ocr/cvBlobsLib/BlobOperators.h \
		farsi_ocr/cvBlobsLib/blob.h \
		/usr/local/include/opencv/cxcore.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/photo.hpp \
		/usr/local/include/opencv2/photo/photo_c.h \
		/usr/local/include/opencv2/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/video/tracking_c.h \
		/usr/local/include/opencv2/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/objdetect.hpp \
		/usr/local/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/include/opencv2/objdetect/objdetect_c.h \
		/usr/local/include/opencv2/calib3d.hpp \
		/usr/local/include/opencv2/core/affine.hpp \
		/usr/local/include/opencv2/calib3d/calib3d_c.h \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/ml.hpp \
		farsi_ocr/cvBlobsLib/BlobLibraryConfiguration.h \
		farsi_ocr/cvBlobsLib/BlobContour.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BlobOperators.o farsi_ocr/cvBlobsLib/BlobOperators.cpp

BlobResult.o: farsi_ocr/cvBlobsLib/BlobResult.cpp farsi_ocr/cvBlobsLib/BlobResult.h \
		farsi_ocr/cvBlobsLib/BlobLibraryConfiguration.h \
		farsi_ocr/cvBlobsLib/ComponentLabeling.h \
		farsi_ocr/cvBlobsLib/BlobContour.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/photo/photo_c.h \
		/usr/local/include/opencv2/video/tracking_c.h \
		/usr/local/include/opencv2/objdetect/objdetect_c.h \
		/usr/local/include/opencv/cxcore.h \
		/usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/photo.hpp \
		/usr/local/include/opencv2/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/objdetect.hpp \
		/usr/local/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/include/opencv2/calib3d.hpp \
		/usr/local/include/opencv2/core/affine.hpp \
		/usr/local/include/opencv2/calib3d/calib3d_c.h \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/ml.hpp \
		/usr/local/include/opencv2/core/core.hpp \
		farsi_ocr/cvBlobsLib/blob.h \
		farsi_ocr/cvBlobsLib/BlobOperators.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BlobResult.o farsi_ocr/cvBlobsLib/BlobResult.cpp

ComponentLabeling.o: farsi_ocr/cvBlobsLib/ComponentLabeling.cpp farsi_ocr/cvBlobsLib/ComponentLabeling.h \
		farsi_ocr/cvBlobsLib/BlobContour.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/photo/photo_c.h \
		/usr/local/include/opencv2/video/tracking_c.h \
		/usr/local/include/opencv2/objdetect/objdetect_c.h \
		/usr/local/include/opencv/cxcore.h \
		/usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/photo.hpp \
		/usr/local/include/opencv2/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/objdetect.hpp \
		/usr/local/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/include/opencv2/calib3d.hpp \
		/usr/local/include/opencv2/core/affine.hpp \
		/usr/local/include/opencv2/calib3d/calib3d_c.h \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/ml.hpp \
		/usr/local/include/opencv2/core/core.hpp \
		farsi_ocr/cvBlobsLib/blob.h \
		farsi_ocr/cvBlobsLib/BlobLibraryConfiguration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ComponentLabeling.o farsi_ocr/cvBlobsLib/ComponentLabeling.cpp

Character.o: farsi_ocr/Character.cpp farsi_ocr/Character.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/photo/photo_c.h \
		/usr/local/include/opencv2/video/tracking_c.h \
		/usr/local/include/opencv2/objdetect/objdetect_c.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Character.o farsi_ocr/Character.cpp

DistanceProfile.o: farsi_ocr/DistanceProfile.cpp farsi_ocr/DistanceProfile.h \
		/usr/local/include/opencv/highgui.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		farsi_ocr/functions.h \
		/usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/photo.hpp \
		/usr/local/include/opencv2/photo/photo_c.h \
		/usr/local/include/opencv2/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/video/tracking_c.h \
		/usr/local/include/opencv2/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/objdetect.hpp \
		/usr/local/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/include/opencv2/objdetect/objdetect_c.h \
		/usr/local/include/opencv2/calib3d.hpp \
		/usr/local/include/opencv2/core/affine.hpp \
		/usr/local/include/opencv2/calib3d/calib3d_c.h \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/ml.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DistanceProfile.o farsi_ocr/DistanceProfile.cpp

functions.o: farsi_ocr/functions.cpp farsi_ocr/functions.h \
		/usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/photo.hpp \
		/usr/local/include/opencv2/photo/photo_c.h \
		/usr/local/include/opencv2/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/video/tracking_c.h \
		/usr/local/include/opencv2/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/objdetect.hpp \
		/usr/local/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/include/opencv2/objdetect/objdetect_c.h \
		/usr/local/include/opencv2/calib3d.hpp \
		/usr/local/include/opencv2/core/affine.hpp \
		/usr/local/include/opencv2/calib3d/calib3d_c.h \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/ml.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o functions.o farsi_ocr/functions.cpp

lettetRecognizer.o: farsi_ocr/lettetRecognizer.cpp farsi_ocr/letterRecognizer.h \
		/usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/photo.hpp \
		/usr/local/include/opencv2/photo/photo_c.h \
		/usr/local/include/opencv2/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/video/tracking_c.h \
		/usr/local/include/opencv2/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/objdetect.hpp \
		/usr/local/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/include/opencv2/objdetect/objdetect_c.h \
		/usr/local/include/opencv2/calib3d.hpp \
		/usr/local/include/opencv2/core/affine.hpp \
		/usr/local/include/opencv2/calib3d/calib3d_c.h \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/ml.hpp \
		/usr/local/include/opencv2/ml/ml.hpp \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/QDir \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qdir.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qstring.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qchar.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qglobal.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qconfig.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qfeatures.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qisenum.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qlogging.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qflags.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_x86.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qatomic_unix.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qmutex.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qnumeric.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qversiontagging.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qbytearray.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qrefcount.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qnamespace.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qarraydata.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qfileinfo.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qfile.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qfiledevice.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qiodevice.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qobject.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qlist.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qiterator.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qhashfunctions.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qpair.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qstringlist.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qregexp.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qmetatype.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qshareddata.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qhash.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/QStringList \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/QDebug \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qdebug.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qmap.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qtextstream.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qlocale.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qvariant.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qvector.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qpoint.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qset.h \
		../../Qt5.6.0/5.6/gcc_64/include/QtCore/qcontiguouscache.h \
		tiny-cnn/tiny_cnn.h \
		tiny-cnn/network.h \
		tiny-cnn/util.h \
		tiny-cnn/activation_function.h \
		tiny-cnn/loss_function.h \
		tiny-cnn/optimizer.h \
		tiny-cnn/layer.h \
		tiny-cnn/product.h \
		tiny-cnn/image.h \
		tiny-cnn/weight_init.h \
		tiny-cnn/layers.h \
		tiny-cnn/input_layer.h \
		tiny-cnn/fully_connected_layer.h \
		tiny-cnn/dropout.h \
		tiny-cnn/average_pooling_layer.h \
		tiny-cnn/partial_connected_layer.h \
		tiny-cnn/convolutional_layer.h \
		tiny-cnn/fully_connected_dropout_layer.h \
		tiny-cnn/max_pooling_layer.h \
		tiny-cnn/mnist_parser.h \
		tiny-cnn/cifar10_parser.h \
		tiny-cnn/deform.h \
		tiny-cnn/display.h \
		farsi_ocr/DistanceProfile.h \
		/usr/local/include/opencv/highgui.h \
		farsi_ocr/functions.h \
		farsi_ocr/cvBlobsLib/BlobResult.h \
		farsi_ocr/cvBlobsLib/BlobLibraryConfiguration.h \
		farsi_ocr/cvBlobsLib/ComponentLabeling.h \
		farsi_ocr/cvBlobsLib/BlobContour.h \
		/usr/local/include/opencv/cv.h \
		/usr/local/include/opencv/cxcore.h \
		/usr/local/include/opencv2/core/core.hpp \
		farsi_ocr/cvBlobsLib/blob.h \
		farsi_ocr/cvBlobsLib/BlobOperators.h \
		/usr/local/include/opencv2/xfeatures2d.hpp \
		/usr/local/include/opencv2/xfeatures2d/nonfree.hpp \
		/usr/local/include/opencv2/xfeatures2d/cuda.hpp \
		/usr/local/include/opencv2/core/cuda.hpp \
		/usr/local/include/opencv2/core/cuda_types.hpp \
		/usr/local/include/opencv2/core/cuda.inl.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lettetRecognizer.o farsi_ocr/lettetRecognizer.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

